<?php

add_action( 'acf/include_fields', function () {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_68e28076203c9',
		'title' => 'Marca / Modello',
		'fields' => array(
			array(
				'key' => 'field_68e28073ba853',
				'label' => 'Produttore',
				'name' => 'produttore_collegato',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'produttore',
				'add_term' => 1,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'field_type' => 'select',
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'multiple' => 0,
				'bidirectional_target' => array(
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => 'modello',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'discussion',
			3 => 'comments',
			4 => 'revisions',
			5 => 'author',
			6 => 'format',
			7 => 'page_attributes',
			8 => 'featured_image',
			9 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_68e00a48a57be',
		'title' => 'Opzioni Veicoli',
		'fields' => array(
			array(
				'key' => 'field_68e00a48e0519',
				'label' => 'Popup "Richiesta Preventivo"',
				'name' => 'popup_richiesta_preventivo',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => 'Seleziona il popup Elementor che mostrerà il form di Richiesta Preventivo.
Il popup deve essere già creato e pubblicato',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'elementor_library',
				),
				'post_status' => '',
				'taxonomy' => array(
					0 => 'elementor_library_type:popup',
				),
				'return_format' => 'object',
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 1,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'impostazioni_veicoli',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'permalink',
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'discussion',
			4 => 'comments',
			5 => 'revisions',
			6 => 'slug',
			7 => 'author',
			8 => 'format',
			9 => 'page_attributes',
			10 => 'featured_image',
			11 => 'categories',
			12 => 'tags',
			13 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_68de9930c2301',
		'title' => 'Specifiche Veicolo',
		'fields' => array(
			array(
				'key' => 'field_68de9931147bf',
				'label' => 'Produttore',
				'name' => 'produttore',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => 'produttore',
				),
				'taxonomy' => 'produttore',
				'add_term' => 1,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'field_type' => 'select',
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'multiple' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_68de99ba147c0',
				'label' => 'Modello',
				'name' => 'modello',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => 'N.b. seleziona prima il Produttore per inserire il Modello',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => 'modello',
				),
				'taxonomy' => 'modello',
				'add_term' => 1,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'field_type' => 'select',
				'allow_null' => 1,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'multiple' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_68de9a22147c3',
				'label' => 'Versione',
				'name' => 'versione',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Opzionale - Specifica dell\'allestimento o versione del modello di auto',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => 'versione',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_68de99d2147c1',
				'label' => 'Cambio',
				'name' => 'cambio',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'cambio',
				'add_term' => 1,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'field_type' => 'radio',
				'allow_null' => 1,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'multiple' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_68de99fa147c2',
				'label' => 'Alimentazione',
				'name' => 'alimentazione',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'alimentazione',
				'add_term' => 1,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'field_type' => 'select',
				'allow_null' => 1,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'multiple' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_68de9d34bbf6d',
				'label' => 'Segmento',
				'name' => 'segmento',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => 'Opzionale - Il segmento viene usato come filtro nella pagina di ricerca',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'segmento',
				'add_term' => 1,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'field_type' => 'select',
				'allow_null' => 1,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'multiple' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_68dfa9f4f10fa',
				'label' => 'Condizione',
				'name' => 'condizione',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => 'Opzionale - Condizione veicolo (Nuovo, Usato, personalizzato)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Nuovo' => 'Nuovo',
					'Usato' => 'Usato',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 1,
				'save_other_choice' => 0,
				'allow_in_bindings' => 0,
				'layout' => 'vertical',
			),
			array(
				'key' => 'field_68e3f3c49f42f',
				'label' => 'Categoria Noleggio',
				'name' => 'categoria_noleggio',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => 'Seleziona la categoria appropriata (obbligatorio)',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => 'categoria_noleggio',
				),
				'taxonomy' => 'categoria_noleggio',
				'add_term' => 0,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'field_type' => 'radio',
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'multiple' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_68de9f60e1075',
				'label' => 'Anticipo',
				'name' => 'anticipo',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_68e3f3c49f42f',
							'operator' => '==',
							'value' => '40',
						),
					),
					array(
						array(
							'field' => 'field_68e3f3c49f42f',
							'operator' => '==',
							'value' => '41',
						),
					),
				),
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'true' => 'Si',
					'false' => 'No',
				),
				'default_value' => 'false',
				'return_format' => 'array',
				'allow_null' => 0,
				'other_choice' => 0,
				'allow_in_bindings' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_68de9fa8e1076',
				'label' => 'Importo Anticipo',
				'name' => 'importo_anticipo',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_68e3f3c49f42f',
							'operator' => '==',
							'value' => '40',
						),
						array(
							'field' => 'field_68de9f60e1075',
							'operator' => '==',
							'value' => 'true',
						),
					),
					array(
						array(
							'field' => 'field_68e3f3c49f42f',
							'operator' => '==',
							'value' => '41',
						),
						array(
							'field' => 'field_68de9f60e1075',
							'operator' => '==',
							'value' => 'true',
						),
					),
				),
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'step' => 1,
				'prepend' => '€',
				'append' => '',
			),
			array(
				'key' => 'field_68dea2ea3ce77',
				'label' => 'Piani Noleggio Lungo Termine',
				'name' => 'piani_noleggio',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_68e3f3c49f42f',
							'operator' => '==',
							'value' => '40',
						),
					),
					array(
						array(
							'field' => 'field_68e3f3c49f42f',
							'operator' => '==',
							'value' => '41',
						),
					),
				),
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 1,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Aggiungi piano di noleggio',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_68dea3023ce78',
						'label' => 'Durata',
						'name' => 'durata',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => 'Numero di mesi totali',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => '',
						'max' => '',
						'allow_in_bindings' => 0,
						'placeholder' => 36,
						'step' => '',
						'prepend' => '',
						'append' => 'mesi',
						'parent_repeater' => 'field_68dea2ea3ce77',
					),
					array(
						'key' => 'field_68dea3863ce79',
						'label' => 'Kilometri',
						'name' => 'kilometri',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => 'Inserisci il numero di kilometri (senza . o ,)',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => '',
						'max' => '',
						'allow_in_bindings' => 0,
						'placeholder' => 40000,
						'step' => '',
						'prepend' => '',
						'append' => 'km',
						'parent_repeater' => 'field_68dea2ea3ce77',
					),
					array(
						'key' => 'field_68dea3f43ce7a',
						'label' => 'Prezzo senza anticipo',
						'name' => 'prezzo_senza_anticipo',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => 'Prezzo mensile senza anticipo (o unico prezzo se anticipo non disponibile)',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => '',
						'max' => '',
						'allow_in_bindings' => 0,
						'placeholder' => 299,
						'step' => '',
						'prepend' => '',
						'append' => '€/mese',
						'parent_repeater' => 'field_68dea2ea3ce77',
					),
					array(
						'key' => 'field_68dea9459d0c2',
						'label' => 'Prezzo con anticipo',
						'name' => 'prezzo_con_anticipo',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => 'Prezzo mensile SE il cliente versa l\'anticipo',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_68de9f60e1075',
									'operator' => '==',
									'value' => 'true',
								),
							),
						),
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => '',
						'max' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'step' => '',
						'prepend' => '',
						'append' => '€/mese',
						'parent_repeater' => 'field_68dea2ea3ce77',
					),
				),
			),
			array(
				'key' => 'field_68e3f524ac348',
				'label' => 'Prezzo Noleggio Breve Termine',
				'name' => 'prezzi_noleggio_breve_termine',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_68e3f3c49f42f',
							'operator' => '==',
							'value' => '42',
						),
					),
				),
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 1,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Aggiungi prezzo/giorni',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_68e3f524ac349',
						'label' => 'Giorni',
						'name' => 'giorni_breve_termine',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => 'Numero di giorni',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => 1,
						'max' => '',
						'allow_in_bindings' => 0,
						'placeholder' => 7,
						'step' => '',
						'prepend' => '',
						'append' => 'giorno/i',
						'parent_repeater' => 'field_68e3f524ac348',
					),
					array(
						'key' => 'field_68e3f524ac34b',
						'label' => 'Prezzo al giorno',
						'name' => 'prezzo_giorno_breve_termine',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => 'Prezzo al giorno per il numero di giorni corrispondente',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => '',
						'max' => '',
						'allow_in_bindings' => 0,
						'placeholder' => 35,
						'step' => '',
						'prepend' => '',
						'append' => '€/giorno',
						'parent_repeater' => 'field_68e3f524ac348',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'veicolo',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => array(
			0 => 'excerpt',
			1 => 'discussion',
			2 => 'comments',
			3 => 'author',
			4 => 'categories',
			5 => 'tags',
			6 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );

add_action( 'init', function () {
	register_taxonomy( 'alimentazione', array(
		0 => 'veicolo',
	), array(
		'labels' => array(
			'name' => 'Alimentazioni',
			'singular_name' => 'Alimentazione',
			'menu_name' => 'Alimentazione',
			'all_items' => 'Tutti/e gli/le Alimentazione',
			'edit_item' => 'Modifica Alimentazione',
			'view_item' => 'Visualizza Alimentazione',
			'update_item' => 'Aggiorna Alimentazione',
			'add_new_item' => 'Aggiungi nuovo/a Alimentazione',
			'new_item_name' => 'Nome del nuovo Alimentazione',
			'search_items' => 'Cerca Alimentazione',
			'popular_items' => 'Alimentazione popolari',
			'separate_items_with_commas' => 'Separa i alimentazione con una virgola',
			'add_or_remove_items' => 'Aggiungi o rimuovi alimentazione',
			'choose_from_most_used' => 'Scegli tra i alimentazione più utilizzati',
			'not_found' => 'Non abbiamo trovato alimentazione',
			'no_terms' => 'Nessun alimentazione',
			'items_list_navigation' => 'Navigazione elenco Alimentazione',
			'items_list' => 'Elenco Alimentazione',
			'back_to_items' => '← Torna a alimentazione',
			'item_link' => 'Link Alimentazione',
			'item_link_description' => 'Un link a alimentazione',
		),
		'public' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'show_admin_column' => true,
		'meta_box_cb' => false,
		'rewrite' => array(
			'with_front' => false,
		),
	) );

	register_taxonomy( 'cambio', array(
		0 => 'veicolo',
	), array(
		'labels' => array(
			'name' => 'Cambio',
			'singular_name' => 'Cambio',
			'menu_name' => 'Cambio',
			'all_items' => 'Tutti/e gli/le Cambio',
			'edit_item' => 'Modifica Cambio',
			'view_item' => 'Visualizza Cambio',
			'update_item' => 'Aggiorna Cambio',
			'add_new_item' => 'Aggiungi nuovo/a Cambio',
			'new_item_name' => 'Nome del nuovo Cambio',
			'search_items' => 'Cerca Cambio',
			'popular_items' => 'Cambio popolari',
			'separate_items_with_commas' => 'Separa i cambio con una virgola',
			'add_or_remove_items' => 'Aggiungi o rimuovi cambio',
			'choose_from_most_used' => 'Scegli tra i cambio più utilizzati',
			'not_found' => 'Non abbiamo trovato cambio',
			'no_terms' => 'Nessun cambio',
			'items_list_navigation' => 'Navigazione elenco Cambio',
			'items_list' => 'Elenco Cambio',
			'back_to_items' => '← Torna a cambio',
			'item_link' => 'Link Cambio',
			'item_link_description' => 'Un link a cambio',
		),
		'public' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'show_admin_column' => true,
		'meta_box_cb' => false,
		'rewrite' => array(
			'with_front' => false,
		),
	) );

	register_taxonomy( 'categoria_noleggio', array(
		0 => 'veicolo',
	), array(
		'labels' => array(
			'name' => 'Categorie Noleggio',
			'singular_name' => 'Categoria Noleggio',
			'menu_name' => 'Categorie Noleggio',
			'all_items' => 'Tutte le Categorie Noleggio',
			'edit_item' => 'Modifica Categoria Noleggio',
			'view_item' => 'Visualizza Categoria Noleggio',
			'update_item' => 'Aggiorna Categoria Noleggio',
			'add_new_item' => 'Aggiungi nuova Categoria Noleggio',
			'new_item_name' => 'Nome della nuovo Categoria Noleggio',
			'search_items' => 'Cerca Categorie Noleggio',
			'popular_items' => 'Categorie Noleggio popolari',
			'separate_items_with_commas' => 'Separa i categorie noleggio con una virgola',
			'add_or_remove_items' => 'Aggiungi o rimuovi categorie noleggio',
			'choose_from_most_used' => 'Scegli tra i categorie noleggio più utilizzati',
			'not_found' => 'Non abbiamo trovato categorie noleggio',
			'no_terms' => 'Nessun categorie noleggio',
			'items_list_navigation' => 'Navigazione elenco Categorie Noleggio',
			'items_list' => 'Elenco Categorie Noleggio',
			'back_to_items' => '← Torna a categorie noleggio',
			'item_link' => 'Link Categoria Noleggio',
			'item_link_description' => 'Un link a categoria noleggio',
		),
		'public' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'show_admin_column' => true,
		'meta_box_cb' => false,
		'rewrite' => array(
			'slug' => 'noleggio',
			'with_front' => false,
		),
		'default_term' => array(
			'name' => 'Lungo Termine',
			'slug' => 'lungo-termine',
		),
	) );

	register_taxonomy( 'modello', array(
		0 => 'veicolo',
	), array(
		'labels' => array(
			'name' => 'Modelli',
			'singular_name' => 'Modello',
			'menu_name' => 'Modelli',
			'all_items' => 'Tutti i Modelli',
			'edit_item' => 'Modifica Modello',
			'view_item' => 'Visualizza Modello',
			'update_item' => 'Aggiorna Modello',
			'add_new_item' => 'Aggiungi nuovo Modello',
			'new_item_name' => 'Nome del nuovo Modello',
			'search_items' => 'Cerca Modelli',
			'popular_items' => 'Modelli popolari',
			'separate_items_with_commas' => 'Separa i modelli con una virgola',
			'add_or_remove_items' => 'Aggiungi o rimuovi modelli',
			'choose_from_most_used' => 'Scegli tra i modelli più utilizzati',
			'not_found' => 'Non abbiamo trovato modelli',
			'no_terms' => 'Nessun modelli',
			'items_list_navigation' => 'Navigazione elenco Modelli',
			'items_list' => 'Elenco Modelli',
			'back_to_items' => '← Torna a modelli',
			'item_link' => 'Link Modello',
			'item_link_description' => 'Un link a modello',
		),
		'description' => 'Modello del veicolo (es. Panda, A1, CLio etc.)',
		'public' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'show_admin_column' => true,
		'meta_box_cb' => false,
		'rewrite' => array(
			'with_front' => false,
		),
	) );

	register_taxonomy( 'produttore', array(
		0 => 'veicolo',
	), array(
		'labels' => array(
			'name' => 'Produttori',
			'singular_name' => 'Produttore',
			'menu_name' => 'Produttori',
			'all_items' => 'Tutti/e gli/le Produttori',
			'edit_item' => 'Modifica Produttore',
			'view_item' => 'Visualizza Produttore',
			'update_item' => 'Aggiorna Produttore',
			'add_new_item' => 'Aggiungi nuovo/a Produttore',
			'new_item_name' => 'Nome del nuovo Produttore',
			'search_items' => 'Cerca Produttori',
			'popular_items' => 'Produttori popolari',
			'separate_items_with_commas' => 'Separa i produttori con una virgola',
			'add_or_remove_items' => 'Aggiungi o rimuovi produttori',
			'choose_from_most_used' => 'Scegli tra i produttori più utilizzati',
			'not_found' => 'Non abbiamo trovato produttori',
			'no_terms' => 'Nessun produttori',
			'items_list_navigation' => 'Navigazione elenco Produttori',
			'items_list' => 'Elenco Produttori',
			'back_to_items' => '← Torna a produttori',
			'item_link' => 'Link Produttore',
			'item_link_description' => 'Un link a produttore',
		),
		'description' => 'Marca auto (es. Audi, BMW, Fiat etc.)',
		'public' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'show_admin_column' => true,
		'meta_box_cb' => false,
		'rewrite' => array(
			'with_front' => false,
		),
	) );

	register_taxonomy( 'segmento', array(
		0 => 'veicolo',
	), array(
		'labels' => array(
			'name' => 'Segmenti',
			'singular_name' => 'Segmento',
			'menu_name' => 'Segmenti',
			'all_items' => 'Tutti/e gli/le Segmenti',
			'edit_item' => 'Modifica Segmento',
			'view_item' => 'Visualizza Segmento',
			'update_item' => 'Aggiorna Segmento',
			'add_new_item' => 'Aggiungi nuovo/a Segmento',
			'new_item_name' => 'Nome del nuovo Segmento',
			'search_items' => 'Cerca Segmenti',
			'popular_items' => 'Segmenti popolari',
			'separate_items_with_commas' => 'Separa i segmenti con una virgola',
			'add_or_remove_items' => 'Aggiungi o rimuovi segmenti',
			'choose_from_most_used' => 'Scegli tra i segmenti più utilizzati',
			'not_found' => 'Non abbiamo trovato segmenti',
			'no_terms' => 'Nessun segmenti',
			'items_list_navigation' => 'Navigazione elenco Segmenti',
			'items_list' => 'Elenco Segmenti',
			'back_to_items' => '← Torna a segmenti',
			'item_link' => 'Link Segmento',
			'item_link_description' => 'Un link a segmento',
		),
		'public' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'show_admin_column' => true,
		'meta_box_cb' => false,
		'rewrite' => array(
			'with_front' => false,
		),
	) );
} );

add_action( 'init', function () {
	register_post_type( 'veicolo', array(
		'labels' => array(
			'name' => 'Veicoli',
			'singular_name' => 'Veicolo',
			'menu_name' => 'Veicoli',
			'all_items' => 'Tutti i Veicoli',
			'edit_item' => 'Modifica Veicolo',
			'view_item' => 'Visualizza Veicolo',
			'view_items' => 'Visualizza Veicoli',
			'add_new_item' => 'Aggiungi nuovo Veicolo',
			'add_new' => 'Aggiungi nuovo Veicolo',
			'new_item' => 'Nuovo Veicolo',
			'parent_item_colon' => 'Veicolo genitore:',
			'search_items' => 'Cerca Veicoli',
			'not_found' => 'Non abbiamo trovato veicoli',
			'not_found_in_trash' => 'Non ci sono veicoli nel cestino',
			'archives' => 'Archivi Veicolo',
			'attributes' => 'Attributi Veicolo',
			'insert_into_item' => 'Inserisci in veicolo',
			'uploaded_to_this_item' => 'Caricato in questo veicolo',
			'filter_items_list' => 'Filtrare l\'elenco di veicoli',
			'filter_by_date' => 'Filtra veicoli per data',
			'items_list_navigation' => 'Navigazione elenco Veicoli',
			'items_list' => 'Elenco Veicoli',
			'item_published' => 'Veicolo pubblicato.',
			'item_published_privately' => 'Veicolo pubblicato privatamente.',
			'item_reverted_to_draft' => 'Veicolo riconvertito in bozza.',
			'item_scheduled' => 'Veicolo programmato.',
			'item_updated' => 'Veicolo aggiornato.',
			'item_link' => 'Link Veicolo',
			'item_link_description' => 'Un link a un veicolo.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_position' => 20,
		'menu_icon' => 'dashicons-car',
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'page-attributes',
			3 => 'thumbnail',
			4 => 'custom-fields',
		),
		'has_archive' => 'veicoli',
		'rewrite' => array(
			'slug' => 'veicoli',
			'feeds' => false,
		),
		'delete_with_user' => false,
	) );
} );

add_action( 'acf/init', function () {
	acf_add_options_page( array(
		'page_title' => 'Opzioni Veicoli',
		'menu_slug' => 'impostazioni_veicoli',
		'parent_slug' => 'edit.php?post_type=veicolo',
		'position' => '',
		'redirect' => false,
		'capability' => 'manage_options',
		'autoload' => true,
	) );
} );

